# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdMaterialFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.FileField(upload_to=b'videoMaterial')),
                ('step', models.IntegerField()),
                ('upload_id', models.CharField(max_length=200)),
                ('upload_time', models.DateTimeField()),
            ],
        ),
    ]
