# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoStudio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admaterialfile',
            name='step',
        ),
        migrations.RemoveField(
            model_name='admaterialfile',
            name='upload_id',
        ),
        migrations.RemoveField(
            model_name='admaterialfile',
            name='upload_time',
        ),
    ]
