# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoStudio', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='vip_url',
            field=models.TextField(null=True),
        ),
    ]
