# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoStudio', '0005_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adName', models.CharField(max_length=200)),
                ('channel', models.CharField(max_length=200)),
                ('loginId', models.CharField(max_length=200)),
                ('siteType', models.CharField(max_length=200)),
                ('category1', models.CharField(max_length=200)),
                ('category2', models.CharField(max_length=200)),
                ('category3', models.CharField(max_length=200)),
                ('insDate', models.DateTimeField()),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=200)),
                ('buyYN', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
