# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoStudio', '0006_auto_20171025_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectGo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vipUrl', models.TextField(null=True)),
                ('hashValue', models.TextField(null=True)),
            ],
        ),
    ]
